### ISSUE TITLE
[Enhancement] Test with nginx -t before applying .conf changes

### ISSUE THREAD

**Issue by Bugsbane** [alexAubin/letsencrypt_ynh#15]
Many people primarily use the web interface. At the same time, this app makes changes to the nginx conf files, which can stop Nginx from starting and prevent access to the web interface.

Really, the install / remove script should, before restarting nginx, run nginx -t to test if the changes are going to break stuff, and roll back to the working config if breakage is detected.

**Comment by M5oul** [comment]
That's a great feature.
We could create an helper which could be used on every apps.
If `nginx -t` test fail, the remove script must be launched.

Edit: I run `sudo nginx -t && sudo service nginx reload` which works fine :wink:

**Comment by alexAubin** [comment]
Okay guys, that sounds cool, but we should really clarify the purpose and timescale of this app, which was meant to be sort of a alpha-stage of the Lets Encrypt support for Yunohost. At some point, a better integration of Let's Encrypt directly into moulinette (I guess ?) was being discussed. I would be glad to better develop this app with something like a web interface to check the status of certificate and add single certificates instead of uninstall/reinstalling if you want to add a single domain... In addition of better securities and checks in the scripts. However that sounds like some work, and that wouldn't work as good as the proper integration into moulinette imho ?

**Comment by TopheC** [comment]
Same Bugsbane's issue for me too. alexAubin is right about the moulinette integration, as a goal.
But... i presume lot a people as used that script (thx for this job alex :) and it works well for a some people. When a change is needed (new domain or certificate renewal) therefore, it "breaks" Yunohost ! And those pepole cannot solve the issue (like me). 
Maybe some work could be done between this statement and the full integration in moulinette, if that goal is voted/decided ?
Otherwise, a clear message about this issue MUST be added to this repo and maybe in the forum, no ? 
I cannot help about coding, I'm just OPS not DEV, but I can participate/test to get around that issue and its french documentation (my english need polish :)

**Comment by Bugsbane** [comment]
It just seems to me that regardless of future integrations etc, that something as conceptually simple as:
cp nginx.con nginx.conf~
if grep "error" | nginx -t !=null {
cp nginx.conf~ nginx.conf;
echo "Oops! Something broke. Reverting."
}

...could save a bunch of people a bunch of unnecessary pain. Obviously I'm simplifying the code there, but not the concept. ;)

**Comment by alexAubin** [comment]
Okay, I'm gonna have a bit a free time in the coming days, so I've started working on a CLI tool (in python) to manage certificates install/check/renewal in yunohost, with the goal of also providing a web front-end. That should allow to better handle checks like "nginx -t" (among other issues which are currently opened). I'm also planning to move to acme-tiny because the official LE client is clearly too heavy for the task it does. So please give me one week or two to come up with a working prototype of this.

I know it's a bit stretching from simply adding the nginx -t check in the current script, but I really don't feel like maintaining this clumsy bash thing I wrote, which was meant to be a temporary solution for the Let's Encrypt install :P.

**Comment by Bugsbane** [comment]
Sounds great. I didn't mean to criticise the work you've done, so much as try to make a suggestion of how to make it better without too much more effort. If you'd like to create something even better, and feel you can do it in just a couple of weeks... well, then I'm very grateful! :dancers:

**Comment by alexAubin** [comment]
No worries, you didn't criticise anything, I'm just not a big fan of having to deal with bash to do complex stuff :P.

**Comment by alexAubin** [comment]
Closing because app is now deprecated thanks to built-in integration in Yunohost 2.5
