### ISSUE TITLE
Consider using 2048 bit key instead of 4096

### ISSUE THREAD

**Issue by mbugeia** [alexAubin/letsencrypt_ynh#2]
Using 4096 key does not add any security since Let's encrypt key is 2048 bit and all 2048 bit key are not close at all to be cracked.
https://gnupg.org/faq/gnupg-faq.html#no_default_of_rsa4096

But the using 4096 bit key does make the key exchange slower and increase the CPU usage.

**Comment by alexAubin** [comment]
I honestly don't know what to think about this. Some guy on a blog was complaining that let's encrypt should put 4096 as the default key size, because people should always use the strongest available thing... On the other hand, people on stack overflow are saying to stick to 2048.... [These guys](https://certsimple.com/blog/measuring-ssl-rsa-keys) quantified the impact on performance of using 4096 instead of 2048 and its pretty small. 

It doesn't seem to matter so much to me ? Or I could put it as an additional option ?
